drive_node_msg:
  ros__parameters:
    speed:
      forward  : 0.0
      left     : 0.0
      right    : 0.0
      backword : 0.0

gripper_node_msg:
  ros__parameters:
    step:
      motor1   : 0.0
      motor2   : 0.0
      motor3   : 0.0
      servo1   : 0.0
      servo2   : 0.0
    absolute:
      x        : 0.0
      y        : 0.0
      z        : 0.0
      roll     : 0.0
      pitch    : 0.0